# Generated by Django 5.2.1 on 2025-05-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipe_images/default.jpg', upload_to='recipe_images/'),
        ),
    ]
